const TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    CALCULATE_TOTAL_PRICE_CART: "CALCULATE_TOTAL_PRICE_CART"
}

export default TYPES;